server:
  port: 8080

spring:
  application:
    name: blog-app

  #  db configurations
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


#Dialect
#driver classname

logging:
  level:
    org.springframework.security: DEBUG