spring.application.name=USERS-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}
spring.profiles.active=dev

# Initial Admin User Configuration
admin.email=${ADMIN_EMAIL:admin@gmail.com}
admin.password=${ADMIN_PASSWORD:admin123}
admin.name=${ADMIN_NAME:Admin User}

