spring.application.name=NOTIFICATIONS-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}
spring.profiles.active=dev

# local mail fallback config
spring.mail.host=${SPRING_MAIL_HOST:localhost}
spring.mail.port=${SPRING_MAIL_PORT:25}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
