apiVersion: apps/v1
kind: Deployment

metadata:
  name: blog-app
  namespace: blog-app

spec:
  replicas: 1
  selector:
    matchLabels:
        app: blog-app

  template:
    metadata:

      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          image: batchlcwd/blog-app:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE

            - name: DB_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: AWS_ACCESS_KEY

            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: AWS_SECRET_KEY

          resources:

            requests:
              memory: "256Mi"
              cpu: "250m"

            limits:
              memory: "512Mi"
              cpu: "500m"


          readinessProbe:

            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 10


          livenessProbe:

            httpGet:
              path: /actuator/health
              port: 8080

            initialDelaySeconds: 40
            periodSeconds: 20
