apiVersion: v1
kind: Service 
metadata:
  name: javatest-service

spec:
  selector:
    app: javatest
  
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080

 # Cluster IP--> within the cluster 
  type: LoadBalancer