# ---------------------------------------------------------
# EKS AUTO MODE - ALB INGRESS CLASS
# ---------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
spec:
  controller: eks.amazonaws.com/alb

---
# ---------------------------------------------------------
# EASYBUY API GATEWAY INGRESS
#
# Internet
#    |
#   ALB
#    |
# Target Group (Pod IPs)
#    |
# api-gateway Service
#    |
# api-gateway Pods
#
# EKS Auto Mode manages the ALB.
# No separate AWS Load Balancer Controller installation needed.
# ---------------------------------------------------------

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: api-gateway
  namespace: easybuy

  annotations:

    # Public ALB
    alb.ingress.kubernetes.io/scheme: internet-facing

    # ALB directly sends traffic to Pod IPs
    alb.ingress.kubernetes.io/target-type: ip

    # HTTP + HTTPS listeners
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

    # Redirect HTTP -> HTTPS
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    # ACM SSL certificate
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:524954473877:certificate/4ccf00c5-f49b-4845-9276-432e1d5707d4

    # ALB health check
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness

    # Health check protocol
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP

    # Health check port = application traffic port
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port

    # Successful health-check codes
    alb.ingress.kubernetes.io/success-codes: "200"

spec:

  ingressClassName: alb

  rules:

    - http:
        paths:

          - path: /
            pathType: Prefix

            backend:
              service:
                name: api-gateway
                port:
                  number: 80