apiVersion: v1
kind: Secret
metadata:
  name: blog-secret
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | quote }}
