apiVersion: v1
kind: Service
metadata:
  name: blogapp-service
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.blogApp.service.type }}
  selector:
    app: blogapp
  ports:
    - protocol: TCP
      port: {{ .Values.blogApp.service.port }}
      targetPort: {{ .Values.blogApp.service.targetPort }}
