spring.application.name=PAYMENT-SERVICE
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}
spring.profiles.active=dev

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_3c1cR1Y1k1x1z1}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:dummy_secret}

