version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_app
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_user

    ports:
      - "3309:3306"

    volumes:
      - mysql_data:/var/lib/mysql
#      - ./mysql/conf.d:/etc/mysql/conf.d

    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

volumes:
  mysql_data: